language: python
sudo: required
dist: precise

install: "sudo apt-get update && sudo apt-get install -y python-dev && pip install -r requirements.txt"
# && pip install -r dev-requirements.txt"
env:
    - TOX_ENV=style
    - TOX_ENV=py27,stats
    - TOX_ENV=py35,stats

script:
  - tox -c tox.ini -e $TOX_ENV

after_success:
  - coveralls
  - codecov
