language: python
sudo: required
dist: trusty
python:
    - '2.7'
    # - '3.5'

before_install:
    - sudo apt update && sudo apt install -y python-dev

install:
    - pip install -r requirements_dev.txt
    - pip install -U tox coveralls codecov
# && pip install -r dev-requirements.txt"
env:
    - TOX_ENV=style
    - TOX_ENV=py27,stats
    # - TOX_ENV=py35,stats
    - TOX_ENV=doc

script:
  - tox -c tox.ini -e $TOX_ENV
  - coverage run --source=dhcpcanon setup.py test

after_success:
  - coveralls
  - codecov
